# GoFrame配置文件
server:
  address: ":8080"
  accessLogEnabled: true
  errorLogEnabled: true
  pprofEnabled: true

# 数据库配置
database:
  default:
    link: "pgsql:postgres:123456@tcp(context-id-backend.zeabur.internal:5432)/contextid?sslmode=disable"
    debug: true


# Casdoor配置
casdoor:
  endpoint: "http://context-id-backend.zeabur.internal:8000"
  externalEndpoint: "https://contextid-backend-dev-casdoor.zeabur.app"
  clientId: "ca09f4429d05c4226155"
  clientSecret: "71a26d426be2d0312fcd2e10a072ebaa1ce51ed0"
  organizationName: "Context-ID"
  applicationName: "Context-ID-DEV"

# Redis配置（可选，用于缓存）
redis:
  default:
    address: "context-id-backend.zeabur.internal:6379"
    db: 0

# 日志配置
logger:
  level: "all"
  stdout: true